/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dungeon(props) {
  const { nodes, materials } = useGLTF("./models/dungeonBuild.gltf");
  return (
    <group {...props} dispose={null}>
      <pointLight
        intensity={2}
        decay={2}
        position={[0, 1.324, -3.989]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials.StoneWall}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027_1.geometry}
        material={materials.PackedDirt}
      />
    </group>
  );
}

useGLTF.preload("./models/dungeonBuild.gltf");
